site_name: Проектирование и дизайн информационных систем
theme:
  name: 'material'
  #feature:
   # tabs: true
nav:
    - Главная: index.md
    - Лекции:
        - Семестр 5:
            - '1. Основные понятия и определения ИС': '1_lecture/lecture.md'
            - '2. Обзор методологий управления проектом': '2_lecture/lecture.md'
    - Практические:
        - Семестр 5:
            - '1. Use-Case диаграмма': '1_lab/lab.md'
            - '2. Установка yii2-user, yii2-rbac': '2_lab/lab.md'
shortcuts:
  help: 191    # ?
  next: 78     # n
  previous: 80 # p
  search: 83   # s
extra_css:
  - css/extra.css
markdown_extensions:
  - admonition
  - codehilite
  - footnotes