site_name: Проектирование и дизайн информационных систем
theme:
  name: 'material'
  #feature:
   # tabs: true
nav:
  - Курсы РТК: index.md
  - МДК 05.02 Разработка:
    - Семестр 4:
      - Лекции:
        - 1. Синтаксис php: '05-02-4/1_lecture/lecture.md'
        - 2. Основные конструкции php[null]: ''
        - 3. Реализация типовых алгоритмов[null]: ''
        - 4. Объекты и классы в ООП: '05-02-4/4_lecture/lecture.md'
        - 5. Конструкторы и деструкторы: '05-02-4/5_lecture/lecture.md'
        - 6. Инкапсуляция, наследование, полиморфизм: '05-02-4/6_lecture/lecture.md'
        - 7. Абстрактные классы. Интерфейсы: '05-02-4/7_lecture/lecture.md'
        - 10. Оформление кода - PSR: '05-02-4/10_lecture/lecture.md'
        - 13. Autoloader + namespace: '05-02-4/13_lecture/lecture.md'
        - 14. Требования к интерфейсу пользователя. Принципы создания графического пользовательского интерфейса (GUI)(S)[null]: '05-02-4/14_lecture/lecture.md'
        - 15. Обоснование выбора технических средств[null]: '05-02-4/15_lecture/lecture.md'
      - Практические и лабораторные :
        - 0. Тест 1 (PHP): '05-02-4/lab/test_php.md'
        - 0. Тест 2 (CSS): '05-02-4/lab/test_html.md'
        - 1. (15) ПР Обоснование выбора технических средств: '05-02-4/lab/1.md'
        - 2. (1) ПР Синтаксис языка программирования: '05-02-4/lab/2.md'
        - 3. (2) ПР Работа со строками: '05-02-4/lab/3.md'
        - 4. ЛР Реализация алгоритмов обработки числовых данных. Отладка приложения: '05-02-4/lab/4.md'
        - 5. (3) ПР Функции для работы с массивами: '05-02-4/lab/5.md'
        - 6. (4) ПР Реализация типовых алгоритмов: '05-02-4/lab/6.md'
        - 7. ЛР Реализация алгоритмов поиска. Отладка приложения: '05-02-4/lab/7.md'
        - 8. ПР Построение и обоснование модели проекта: '05-02-4/lab/8.md'
        - 9. ПР Стоимостная оценка проекта: '05-02-4/lab/9.md'
        - 10. ЛР Построение диаграммы Вариантов использования и диаграммы. Последовательности и генерация кода[null]: '#'
        - 11. (5) ПР Создание класса: '05-02-4/lab/11.md'
        - 12. ПР Работа с объектами класса[null]: '#'
        - 13. ЛР Разработка приложений для моделирования процессов и явлений. Отладка приложения[null]: '#'
        - 14. (6) ПР Классы, работа с конструктором: '05-02-4/lab/14.md'
        - 15. ЛР Разработка и отладка генератора случайных символов[null]: '#'
        - 16. ЛР Построение диаграммы Деятельности, диаграммы Состояний и диаграммы Классов и генерация кода[null]: '#'
        - 17. ЛР Установка и настройка системы контроля версий с разграничением ролей[null]: '#'
        - 18. ЛР Реализация обработки табличных данных. Отладка приложения: '05-02-4/lab/18.md'
        - 19. ЛР Интеграция модуля в информационную систему[null]: '#'
        - 20. ЛР Построение диаграмм потоков данных и генерация кода[null]: '#'
        - 21. ЛР Построение диаграммы компонентов и генерация кода[null]: '#'
        - 22. ЛР Построение диаграммы Кооперации и диаграммы Развертывания и генерация кода[null]: '#'
        - 23. ЛР Программирование обмена сообщениями между модулями[null]: '#'
        - 24. (7) ЛР Организация файлового ввода-вывода данных: '05-02-4/lab/24.md'
        - 25. ЛР Разработка модулей экспертной системы[null]: '#'
        - 26. ЛР Создание сетевого сервера и сетевого клиента[null]: '#'
        - 27. ЛР Проектирование и разработка интерфейса пользователя»[null]: '#'
        - 28. ЛР Разработка графического интерфейса пользователя: '05-02-4/lab/28.md'
        - 29. ДОП ПР Наследование: '05-02-4/lab/29d.md'
        - 30. ДОП ПР Система контроля версий: '05-02-4/lab/30d.md'
        - 31. ДОП ПР Оформление кода: '05-02-4/lab/31d.md'
        - 32. ДОП ПР Cоздание сайта: '05-02-4/lab/32d.md'
        - 33. ДОП ПР Autoloader + namespace: '05-02-4/lab/33d.md'


    - Семестр 5: ''
  - МДК 05.01 Проектирование (дизайн):
    - Семестр 4:
      - Лекции:
        - '1. Основные понятия и определения ИС': '05-01-4/1_lecture/lecture.md'
        - '2. Обзор методологий разработки систем': '05-01-4/2_lecture/lecture.md'
        - '3. Диаграмма use-case': ''
        - '4. Моделирование поведения (часть 1)': '05-01-4/4_lecture/lecture.md'
        - '5. Моделирование поведения (часть 2)':
          - '5.1 Моделирование поведения (презентация)': '05-01-4/5_lecture/lecture.md'
          - '5.2 Моделирование поведения (лекция) [null]' : ''
        - '6. Разработка руководства по инсталляции программного средства по индивидуальному заданию[null]' : ''
        - '7. Пользовательские истории (User Story)[null]': ''
      - Практические и лабораторные:
        - '1. Use-Case диаграмма': '05-01-4/1_lab/lab.md'
        - '4. Моделирование поведения (часть 1)': '05-01-4/4_lab/lab.md'
        - '5. Моделирование поведения (часть 2)': '05-01-4/5_lab/lab.md'
        - '6. Разработка руководства по инсталляции программного средства по индивидуальному заданию': '05-01-4/6_lab/lab.md'
        - '7. Диаграмма классов': '05-01-4/7_lab/lab.md'
      - Семестр 5:
        - '2. Установка yii2-user, yii2-rbac': '05-01-5/2_lab/lab.md'
        - '3. Gii, поведения и права доступа': '05-01-5/3_lab/lab.md'
  - 'МДК.03.02 Инструментальные средства разработки' : ''
  - 'МДК.02.03 Организация администрирования' : ''
  - 'HTML, CSS/SCSS, GIT' : ''
shortcuts:
  help: 191    # ?
  next: 78     # n
  previous: 80 # p
  search: 83   # s
extra_css:
  - css/extra.css
markdown_extensions:
  - admonition
  - codehilite
  - footnotes