site_name: Проектирование и дизайн информационных систем
theme:
  name: 'material'
  #feature:
   # tabs: true
nav:
  - Главная: index.md
  - МДК 05.02 Разработка:
    - Семестр 4:
      - Лекции:
        - 1. Синтаксис php: ''
        - 2. Основные конструкции php: ''
        - 3. Реализация типовых алгоритмов: ''
        - 4. Объекты и классы в ООП: ''
        - 5. Конструкторы и деструкторы: ''
      - Практические и лабораторные :
        - 1. ПР Ситаксис, математические опреации, типы данных: '05-02-4/1_lab/lab.md'
        - 2. ПР Работа со строками: '05-02-4/2_lab/lab.md'
        - 3. ПР Функции для работы с массивами: '05-02-4/3_lab/lab.md'
        - 4. ПР Реализация типовых алгоритмов: '05-02-4/4_lab/lab.md'
        - 5. ПР Создание класса: '05-02-4/5_lab/lab.md'
        - 6. ПР Классы, работа с конструктором: '05-02-4/6_lab/lab.md'
        - 7. ПР Передача параметров методами GET, POST: '05-02-4/7_lab/lab.md'
    - Семестр 5: ''
  - МДК 05.01 Проектирование (дизайн):
    - Лекции:
      - Семестр 5:
        - '1. Основные понятия и определения ИС': '1_lecture/lecture.md'
        - '2. Обзор методологий разработки систем': '2_lecture/lecture.md'
        - '3. Пользовательские истории (User Story)': ''
      - Практические и лабораторные: ''
      - Семестр 5:
        - '1. Use-Case диаграмма': '1_lab/lab.md'
        - '2. Установка yii2-user, yii2-rbac': '2_lab/lab.md'
        - '3. Gii, поведения и права доступа': '3_lab/lab.md'
shortcuts:
  help: 191    # ?
  next: 78     # n
  previous: 80 # p
  search: 83   # s
extra_css:
  - css/extra.css
markdown_extensions:
  - admonition
  - codehilite
  - footnotes